version: '3.8'

services:
  bengali-rag:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./questions.csv:/app/questions.csv:ro
      - ./embeddings.pkl:/app/embeddings.pkl
      - ./embeddings_index.pkl:/app/embeddings_index.pkl
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
